In [7]:
import numpy as np
import pandas as pd

df = pd.read_csv("/content/01 covid_toy - 01 covid_toy.csv")

df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
x = df.iloc[:,0:5]
y = df.drop(x,axis = 'columns')
print(x.head())
print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [17]:
# Train-Test split

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)
print(x_train.head())

    age  gender  fever   cough       city
3    31  Female   98.0    Mild    Kolkata
48   66    Male   99.0  Strong  Bangalore
91   38    Male    NaN    Mild      Delhi
29   34  Female    NaN  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

In [21]:
# Without column transformer.

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [26]:
from sklearn.preprocessing import LabelEncoder

si = SimpleImputer()
le = LabelEncoder()

In [34]:
# Ordinal encoding cough

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

x_train['cough'] = oe.fit_transform(x_train[['cough']])
x_test['cough'] = oe.transform(x_test[['cough']])

In [35]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.transform(y_test.has_covid)

In [36]:
x_train['fever'] = si.fit_transform(x_train[['fever']])
x_test['fever'] = si.transform(x_test[['fever']])

In [38]:
# OHE on City and gender

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(drop='first', sparse_output=False)

x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)

(80, 4)